-- export_schema.sql
-- Portable schema export (creates tables, PKs, FKs). Run as a DB owner.

-- Create table: notes
CREATE TABLE IF NOT EXISTS public.notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at date,
  subject varchar,
  topic varchar,
  notes text
);

-- Create table: questions
CREATE TABLE IF NOT EXISTS public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at date,
  question text,
  main_id bigint
);

-- Foreign key: questions.main_id -> notes.id
ALTER TABLE IF EXISTS public.questions
  ADD CONSTRAINT questions_main_id_fkey
  FOREIGN KEY (main_id)
  REFERENCES public.notes (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;